import './globals.css'
import { Ubuntu } from 'next/font/google'
import Link from 'next/link';
import Header from '@/components/Header';

const ubuntu = Ubuntu ({ 
  weight: ['300', '400'],
  subsets: ['latin'] }
);

export const metadata = {
  title: 'Litty.Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header></Header>
        <main className='container'>{children}</main>
      </body>
    </html>
  )
}
